# build settings

#theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes@4.22.0
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: dark

include: [api, tut]

# customization settings
subtitle: 0.6.1
name: centau
description: An ECS library for Luau.
baseurl: /ecr
url: http://centau.github.io
repository: centau/ecr
logo: /assets/images/logo.svg
breadcrumbs: false
search: true
lunr:
  search_within_pages: true

defaults:
  # api
  - scope:
      path: /api/*
      type: pages
    values:
      layout: single
      toc: true
      toc_label: Contents
      toc_icon: list
      toc_sticky: true
      sidebar:
        nav: api
  # tut
  - scope:
      path: /tut/*
      type: pages
    values:
      layout: single
      toc: true
      toc_label: Contents
      toc_icon: list
      toc_sticky: true
      sidebar:
        nav: tut
